name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-cov
        
    - name: Run installation test
      run: python test_install.py
      
    - name: Run unit tests
      run: pytest tests/ -v --cov=assetx
      
    - name: Test CLI
      run: |
        python -m assetx.cli --help
        python -m assetx.cli meta --help

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 mypy
        pip install -e .
        
    - name: Run black
      run: black --check assetx/
      
    - name: Run isort
      run: isort --check-only assetx/
      
    - name: Run flake8
      run: flake8 assetx/
      
    - name: Run mypy
      run: mypy assetx/ --ignore-missing-imports
